apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: static-web
  template:
    metadata:
      labels:
        app: static-web
    spec:
      containers:
      - name: web
        image: srilekya/static-web-app:v3
        ports:
        - containerPort: 80
